version: "3"

services:
  api:
    command: yarn dev
    environment:
      NODE_ENV: development
      PORT: 3000
      EMIRATES_API_URI: https://www.emirates.com
      COUNTRY_CODE_API_URI: https://restcountries.eu/rest/v2/all
      REDIS_URI: redis://redis/1
    image: node
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./api:/www
    working_dir: /www

  web:
    command: yarn dev
    environment:
      REACT_APP_API_URI: http://localhost:3000/api
      REACT_APP_DEBOUNCE_TIME: 300
      REACT_APP_CACHE_TIME: 30000
    image: node
    ports:
      - 3030:3000
    volumes:
      - ./web:/www
    working_dir: /www

  redis:
    image: redis
